# Generated by Django 5.2.11 on 2026-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_petsubscription_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcher',
            name='closing_time',
            field=models.CharField(default='09:00 PM', max_length=20),
        ),
        migrations.AddField(
            model_name='butcher',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='butcher',
            name='opening_time',
            field=models.CharField(default='06:00 AM', max_length=20),
        ),
    ]
