# Generated by Django 5.2.11 on 2026-02-16 08:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_butcher_closing_time_butcher_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='aichathistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Chat History', 'verbose_name_plural': 'AI Chat Histories'},
        ),
        migrations.AlterModelOptions(
            name='butcher',
            options={'verbose_name': 'Butcher', 'verbose_name_plural': 'Butchers'},
        ),
        migrations.AlterModelOptions(
            name='gymsubscription',
            options={'verbose_name': 'Gym Subscription', 'verbose_name_plural': 'Gym Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='meatitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meat Item', 'verbose_name_plural': 'Meat Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='petsubscription',
            options={'verbose_name': 'Pet Subscription', 'verbose_name_plural': 'Pet Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-next_run_date'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='villagesource',
            options={'verbose_name': 'Village Source', 'verbose_name_plural': 'Village Sources'},
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation if applicable', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was delivered', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID for online payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment completion status', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time status was updated'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default delivery address?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Street address, house number', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(help_text='Postal code', max_length=10),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='context',
            field=models.CharField(choices=[('PET', 'Pet Nutrition'), ('GYM', 'Gym/Fitness'), ('GENERAL', 'General Shopping')], default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='message',
            field=models.TextField(help_text="User's question"),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='response',
            field=models.TextField(help_text="AI's response"),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the shop currently accepting orders?'),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='service_radius_km',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Delivery radius in kilometers', max_digits=5),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='shop_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='user',
            field=models.OneToOneField(help_text='User account managing this shop', on_delete=django.db.models.deletion.CASCADE, related_name='butcher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='butcher',
            name='village_source',
            field=models.ForeignKey(blank=True, help_text='Primary source of meat (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butchers', to='api.villagesource'),
        ),
        migrations.AlterField(
            model_name='meatitem',
            name='butcher',
            field=models.ForeignKey(help_text='Butcher shop selling this item', on_delete=django.db.models.deletion.CASCADE, related_name='meat_items', to='api.butcher'),
        ),
        migrations.AlterField(
            model_name='meatitem',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meatitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='meatitem',
            name='quantity',
            field=models.IntegerField(help_text='Available stock quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meatitem',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD_OUT', 'Sold Out'), ('HIDDEN', 'Hidden')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='butcher',
            field=models.ForeignKey(help_text='Butcher fulfilling the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.butcher'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(help_text='Full delivery address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment'), ('UPI', 'UPI'), ('CARD', 'Card')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total order value in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meat_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.meatitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit at the time of order', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True, help_text='Is subscription currently running?'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_sunday_special',
            field=models.BooleanField(default=False, help_text='Sunday 7-9 AM special slot'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='meat_item_name',
            field=models.CharField(help_text='Snapshot of item name at subscription time', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_run_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.CharField(help_text='e.g. Weekly, Bi-weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or notes', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For age verification and birthday offers', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(help_text="User's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text="User's last name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number for order updates', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_butcher_id',
            field=models.IntegerField(blank=True, help_text="ID of the user's favorite butcher", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Link to profile picture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Linked Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='villagesource',
            name='description',
            field=models.TextField(blank=True, help_text='Details about farming practices', null=True),
        ),
        migrations.AlterField(
            model_name='villagesource',
            name='location',
            field=models.CharField(help_text='Geographic location', max_length=255),
        ),
        migrations.AlterField(
            model_name='villagesource',
            name='name',
            field=models.CharField(help_text='Name of the village or farm source', max_length=100),
        ),
        migrations.AddIndex(
            model_name='butcher',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_geo'),
        ),
        migrations.AddIndex(
            model_name='butcher',
            index=models.Index(fields=['is_available', 'status'], name='idx_available_status'),
        ),
        migrations.AddIndex(
            model_name='butcher',
            index=models.Index(fields=['status', 'created_at'], name='idx_status_created_butcher'),
        ),
        migrations.AddIndex(
            model_name='meatitem',
            index=models.Index(fields=['butcher', 'status'], name='idx_butcher_status'),
        ),
        migrations.AddIndex(
            model_name='meatitem',
            index=models.Index(fields=['category', 'status'], name='idx_category_status'),
        ),
        migrations.AddIndex(
            model_name='meatitem',
            index=models.Index(fields=['butcher', 'price'], name='idx_butcher_price'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='idx_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['butcher', '-created_at'], name='idx_butcher_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'active'], name='idx_user_active_sub'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_run_date', 'active'], name='idx_next_run_active'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['butcher', 'active'], name='idx_butcher_active'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone'], name='idx_phone'),
        ),
        migrations.AddConstraint(
            model_name='meatitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='meatitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='positive_total'),
        ),
    ]
