# Generated by Django 5.2.11 on 2026-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcher',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Is this the MeatHub Official Flagship store?'),
        ),
    ]
