# Generated by Django 5.2.11 on 2026-02-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_butcher_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatitem',
            name='village_source',
            field=models.ForeignKey(blank=True, help_text='Traceability: where was this meat sourced?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meat_items', to='api.villagesource'),
        ),
    ]
