# Generated by Django 5.2.11 on 2026-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meatitem_village_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cutting_video_url',
            field=models.URLField(blank=True, help_text='Link to the cutting proof video (USP)', max_length=500, null=True),
        ),
    ]
