# Generated by Django 5.2.11 on 2026-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_status_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsubscription',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='petsubscription',
            name='delivery_address',
            field=models.TextField(),
        ),
    ]
