# Generated by Django 5.2.11 on 2026-02-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_gymsubscription_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('ingredients', models.TextField(help_text='Detailed listing of organs/cuts used')),
                ('is_vet_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='training_goal',
            field=models.CharField(choices=[('CUT', 'Cut / Lean'), ('BULK', 'Bulk / Gain'), ('MAINTAIN', 'Maintenance')], default='MAINTAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='meatitem',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meatitem',
            name='fat_g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='meatitem',
            name='is_gym_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meatitem',
            name='is_pet_suitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meatitem',
            name='product_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FITNESS', 'Fitness'), ('PET', 'Pet')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='meatitem',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='ButcherWasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(help_text='e.g. Chicken Frames, Mutton Bones', max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('butcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_listings', to='api.butcher')),
            ],
        ),
    ]
