# Generated by Django 5.2.11 on 2026-02-19 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_petfoodproduct_gymsubscription_training_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcher',
            name='hygiene_score',
            field=models.IntegerField(default=5, help_text='1-5 Shells rating based on audit', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='butcher',
            name='live_stream_url',
            field=models.URLField(blank=True, help_text='YouTube Live embed URL (Only for flagship store)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='skip_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates to skip'),
        ),
        migrations.AddField(
            model_name='petsubscription',
            name='skip_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates to skip'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='skip_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates (ISO format) to skip delivery'),
        ),
    ]
