# Generated by Django 5.2.11 on 2026-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_butcher_hygiene_score_butcher_live_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sunday_special',
            field=models.BooleanField(default=False, help_text='Flag for weekly Sunday pre-orders'),
        ),
    ]
