# Generated by Django 5.2.11 on 2026-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_is_sunday_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sunday_slot',
            field=models.CharField(blank=True, choices=[('EARLY_MORNING', '6 AM - 8 AM'), ('MORNING', '8 AM - 10 AM'), ('LATE_MORNING', '10 AM - 12 PM')], help_text='Preferred time slot for Sunday deliveries', max_length=50, null=True),
        ),
    ]
