# Generated by Django 5.2.11 on 2026-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_loyalty_points_userprofile_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcher',
            name='daily_order_quota',
            field=models.IntegerField(default=50, help_text='Maximum orders allowed per day'),
        ),
    ]
