# Generated by Django 5.2.11 on 2026-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_butcher_daily_order_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcher',
            name='active_orders',
            field=models.IntegerField(default=0, help_text='Current number of active/pending orders'),
        ),
        migrations.AddField(
            model_name='butcher',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='Manual or auto-flag for load balancing'),
        ),
    ]
