# Generated by Django 5.2.11 on 2026-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_butcher_active_orders_butcher_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_history',
            field=models.JSONField(blank=True, default=list, help_text='Historical record of status changes'),
        ),
    ]
