# Generated by Django 5.2.11 on 2026-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_user_lat_order_user_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butcher',
            name='is_gym_approved',
            field=models.BooleanField(default=False, help_text='Certified for high-protein gym subscriptions'),
        ),
    ]
