-- Create all databases
CREATE DATABASE IF NOT EXISTS meathub_auth;
CREATE DATABASE IF NOT EXISTS meathub_user;
CREATE DATABASE IF NOT EXISTS meathub_butcher;
CREATE DATABASE IF NOT EXISTS meathub_order;
CREATE DATABASE IF NOT EXISTS meathub_subscription;
CREATE DATABASE IF NOT EXISTS meathub_delivery;
CREATE DATABASE IF NOT EXISTS meathub_gym;
CREATE DATABASE IF NOT EXISTS meathub_pet;
CREATE DATABASE IF NOT EXISTS meathub_media;
CREATE DATABASE IF NOT EXISTS meathub_admin;
CREATE DATABASE IF NOT EXISTS meathub_notification;
CREATE DATABASE IF NOT EXISTS meathub_ai;
CREATE DATABASE IF NOT EXISTS meathub_blockchain;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
